global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.  
scrape_configs:
  - job_name: 'fastify' 
    static_configs:
    - targets: ['host.docker.internal:3000'] #Our express app container
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']